builds:
  - main: ./cmd/datadog-apm-dumper
    binary: datadog-apm-dumper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
checksum:
  name_template: 'datadog-apm-dumper-checksums.txt'
archives:
  - name_template: "datadog-apm-dumper-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
